services:
  api:
    image:
      scarletbobcat/nail-art:api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  client:
    image:
      scarletbobcat/nail-art:client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
