spring.config.import=optional:classpath:.env[.properties]

spring.data.mongodb.uri=${DEV_MONGO_URI}

spring.datasource.url=jdbc:postgresql://localhost:5432/nail_art
spring.datasource.username=nail_art
spring.datasource.password=nail_art_password

frontend.url=${DEV_FRONTEND_URL}