spring.config.import=optional:classpath:.env[.properties]

app.mongodb.uri=${DEV_MONGO_URI:mongodb://localhost:27017/nail_art}

spring.datasource.url=jdbc:postgresql://localhost:5432/nail_art
spring.datasource.username=nail_art
spring.datasource.password=nail_art_password

frontend.url=${DEV_FRONTEND_URL}
